In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
#"/content/drive/MyDrive/train.csv"
#"/content/drive/MyDrive/test.csv"

In [3]:
pip install transformers

In [4]:
pip install datasets

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 472.7/472.7 kB 33.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 14.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 12.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.1/194.1 kB 18.0 MB/s eta 0:00:00


In [5]:
import pandas as pd
import numpy as np
from datasets import Dataset
from transformers import DistilBertTokenizer, DistilBertModel, Trainer, TrainingArguments
import torch
import torch.nn as nn
from sklearn.metrics import f1_score
from sklearn.model_selection import train_test_split

# Load data
train_data = pd.read_csv("/content/drive/MyDrive/train.csv")

# Define emotion columns
emotion_columns = ['anger', 'anticipation', 'disgust', 'fear', 'joy', 'love', 'optimism', 'pessimism', 'sadness', 'surprise', 'trust']

# Initialize tokenizer
tokenizer = DistilBertTokenizer.from_pretrained('distilbert-base-uncased')

# Split the DataFrame
train_df, val_df = train_test_split(train_data, test_size=0.2, random_state=42)

# Convert to Dataset
train_dataset = Dataset.from_pandas(train_df)
val_dataset = Dataset.from_pandas(val_df)

print("Train dataset size:", len(train_dataset))
print("Val dataset size:", len(val_dataset))



/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/483 [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(


Train dataset size: 6179
Val dataset size: 1545


In [6]:
def calculate_class_weights(label_counts, total_samples):
    # Option 1: Inverse of class frequency
    weights_inverse = total_samples / label_counts

    # Option 2: Logarithmic scaling
    weights_log = 1 + np.log(total_samples / label_counts)

    # Option 3: Square root of inverse frequency
    weights_sqrt = np.sqrt(total_samples / label_counts)

    return {
        'inverse': weights_inverse,
        'log': weights_log,
        'sqrt': weights_sqrt
    }

In [7]:
# Tokenize function
def tokenize_function(examples):
    return tokenizer(examples['Tweet'], truncation=True, padding='max_length', max_length=128)

# Prepare labels
def prepare_labels(examples):
    labels = []
    for i in range(len(examples[emotion_columns[0]])):
        label = [float(examples[col][i] not in ['NONE', '0', 0]) for col in emotion_columns]
        labels.append(label)
    examples['labels'] = labels
    return examples

# Apply tokenization and label preparation
train_dataset = train_dataset.map(tokenize_function, batched=True)
val_dataset = val_dataset.map(tokenize_function, batched=True)

train_dataset = train_dataset.map(prepare_labels, batched=True)
val_dataset = val_dataset.map(prepare_labels, batched=True)

# Remove unnecessary columns
columns_to_remove = [col for col in train_dataset.column_names if col not in ['input_ids', 'attention_mask', 'labels']]
train_dataset = train_dataset.remove_columns(columns_to_remove)
val_dataset = val_dataset.remove_columns(columns_to_remove)



Map:   0%|          | 0/6179 [00:00<?, ? examples/s]

Map:   0%|          | 0/1545 [00:00<?, ? examples/s]

Map:   0%|          | 0/6179 [00:00<?, ? examples/s]

Map:   0%|          | 0/1545 [00:00<?, ? examples/s]

In [8]:
# Set format
train_dataset.set_format(type='torch', columns=['input_ids', 'attention_mask', 'labels'])
val_dataset.set_format(type='torch', columns=['input_ids', 'attention_mask', 'labels'])

# Check label distribution
print("\nLabel distribution in train dataset:")
train_labels = np.array([sample['labels'] for sample in train_dataset])
print(train_labels.sum(axis=0))

print("\nLabel distribution in val dataset:")
val_labels = np.array([sample['labels'] for sample in val_dataset])
print(val_labels.sum(axis=0))

# Calculate class weights
label_counts = np.sum(train_labels, axis=0)
total_samples = len(train_dataset)
class_weights = total_samples / (len(emotion_columns) * label_counts)
class_weights = torch.tensor(class_weights, dtype=torch.float)




Label distribution in train dataset:
[2287.  880. 2325. 1058. 2318.  681. 1858.  708. 1813.  326.  308.]

Label distribution in val dataset:
[572. 222. 596. 305. 559. 151. 433. 187. 460.  70.  92.]


In [9]:
# Calculate label counts and total samples
label_counts = np.sum(train_labels, axis=0)
total_samples = len(train_dataset)

# Calculate class weights
class_weights = calculate_class_weights(label_counts, total_samples)

# Choose a weighting scheme (you can change this to 'log' or 'sqrt' to try different schemes)
chosen_weights = 'inverse'

# Convert to tensor
class_weights_tensor = torch.tensor(class_weights[chosen_weights], dtype=torch.float)

# Update the model definition
class MultiLabelClassification(nn.Module):
    def __init__(self, num_labels, class_weights):
        super().__init__()
        self.distilbert = DistilBertModel.from_pretrained('distilbert-base-uncased')
        self.dropout = nn.Dropout(0.1)
        self.classifier = nn.Linear(self.distilbert.config.hidden_size, num_labels)
        self.loss_fct = nn.BCEWithLogitsLoss(pos_weight=class_weights)

    def forward(self, input_ids, attention_mask, labels=None):
        outputs = self.distilbert(input_ids=input_ids, attention_mask=attention_mask)
        pooled_output = outputs.last_hidden_state[:, 0]  # Use [CLS] token
        pooled_output = self.dropout(pooled_output)
        logits = self.classifier(pooled_output)

        loss = None
        if labels is not None:
            loss = self.loss_fct(logits, labels)

        return {'loss': loss, 'logits': logits}

# Initialize the model with class weights
model = MultiLabelClassification(num_labels=len(emotion_columns), class_weights=class_weights_tensor)

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

In [10]:
# Training arguments
training_args = TrainingArguments(
    output_dir='./results_distilbert',
    num_train_epochs=10,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=64,
    warmup_steps=500,
    weight_decay=0.01,
    logging_dir='./logs_distilbert',
    logging_steps=100,
    evaluation_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="macro_f1",
    learning_rate=2e-5,
    remove_unused_columns=False,
)


/usr/local/lib/python3.10/dist-packages/transformers/training_args.py:1525: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(


In [11]:
# Compute metrics function
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = torch.sigmoid(torch.Tensor(logits)).numpy()

    print("Predictions shape:", predictions.shape)
    print("Labels shape:", labels.shape)
    print("Sample predictions (first 5):")
    print(predictions[:5])
    print("Sample labels (first 5):")
    print(labels[:5])

    thresholds = [0.1, 0.3, 0.5]
    for threshold in thresholds:
        binary_predictions = (predictions > threshold).astype(float)
        f1_scores = f1_score(labels, binary_predictions, average=None, zero_division=1)
        macro_f1 = np.mean(f1_scores)

        print(f"\nThreshold: {threshold}")
        for i, score in enumerate(f1_scores):
            print(f"F1 score for label {i}: {score}")
        print(f"Macro F1: {macro_f1}")

    # Use 0.5 as the final threshold
    final_predictions = (predictions > 0.5).astype(float)
    final_f1_scores = f1_score(labels, final_predictions, average=None, zero_division=1)
    final_macro_f1 = np.mean(final_f1_scores)
    final_micro_f1 = f1_score(labels, final_predictions, average='micro', zero_division=1)

    print(f"\nFinal Macro F1: {final_macro_f1}")
    print(f"Final Micro F1: {final_micro_f1}")

    return {
        'macro_f1': final_macro_f1,
        'micro_f1': final_micro_f1
    }

# Initialize Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    compute_metrics=compute_metrics,
)

In [12]:
# Train the model
trainer.train()

wandb: WARNING The `run_name` is currently set to the same value as `TrainingArguments.output_dir`. If this was not intended, please specify a different run name by setting the `TrainingArguments.run_name` parameter.
wandb: Using wandb-core as the SDK backend. Please refer to https://wandb.me/wandb-core for more information.


<IPython.core.display.Javascript object>

wandb: Logging into wandb.ai. (Learn how to deploy a W&B server locally: https://wandb.me/wandb-server)
wandb: You can find your API key in your browser here: https://wandb.ai/authorize
wandb: Paste an API key from your profile and hit enter, or press ctrl+c to quit:

 ··········


wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc


Predictions shape: (1545, 11)
Labels shape: (1545, 11)
Sample predictions (first 5):
[[0.19743045 0.5428157  0.19006132 0.28461105 0.8764328  0.71788454
  0.88727385 0.30345476 0.39554733 0.33069786 0.6585058 ]
 [0.17088583 0.38306385 0.150981   0.18124224 0.9197885  0.88489574
  0.8923694  0.28394535 0.31248504 0.37474558 0.64913267]
 [0.21372065 0.6192254  0.16212091 0.15957205 0.90138733 0.8573862
  0.8387854  0.17150229 0.1488073  0.40214318 0.5126985 ]
 [0.80106276 0.21295546 0.80428886 0.7253762  0.1731688  0.11053491
  0.16373028 0.75623    0.82491785 0.33184385 0.12388735]
 [0.5906925  0.69797856 0.55909586 0.3671633  0.4883327  0.19720343
  0.50196224 0.2505303  0.42686328 0.509802   0.26385772]]
Sample labels (first 5):
[[0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 0.]
 [1. 0. 1. 1. 0. 0. 0. 1. 1. 0. 0.]
 [1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]

Threshold: 0.1
F1 score for label 0: 0.5403873405762872
F1 score for label 1: 

TrainOutput(global_step=3870, training_loss=0.5567165828182408, metrics={'train_runtime': 8144.807, 'train_samples_per_second': 7.586, 'train_steps_per_second': 0.475, 'total_flos': 0.0, 'train_loss': 0.5567165828182408, 'epoch': 10.0})

In [13]:
# Evaluate on validation set
val_results = trainer.evaluate()
print("Validation results:", val_results)
columns_to_keep = ['input_ids', 'attention_mask', 'labels']


Predictions shape: (1545, 11)
Labels shape: (1545, 11)
Sample predictions (first 5):
[[0.05713119 0.6554288  0.04188733 0.24730913 0.8840414  0.07049593
  0.9906607  0.05597795 0.104092   0.01770191 0.66326445]
 [0.01503284 0.09202892 0.01690882 0.08614612 0.9730618  0.47693178
  0.9494569  0.04386844 0.12317201 0.03977552 0.08123233]
 [0.11158185 0.7668315  0.06191171 0.02038323 0.97259766 0.41515562
  0.8725812  0.02321049 0.03010539 0.05337052 0.071403  ]
 [0.95386195 0.04153059 0.966279   0.12790552 0.02831809 0.02396318
  0.01885992 0.77637225 0.95993906 0.0360078  0.02475352]
 [0.97445655 0.36027578 0.93441844 0.02937776 0.07611444 0.01694641
  0.07243548 0.11022153 0.47425407 0.03079503 0.01580536]]
Sample labels (first 5):
[[0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 0.]
 [1. 0. 1. 1. 0. 0. 0. 1. 1. 0. 0.]
 [1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]

Threshold: 0.1
F1 score for label 0: 0.671865626874625
F1 score for label 1: 

In [14]:
from torch.utils.data import DataLoader
test_data = pd.read_csv("/content/drive/MyDrive/test.csv")
# Assuming you've already prepared your test_dataset as before
test_dataset = Dataset.from_pandas(test_data)
test_dataset = test_dataset.map(tokenize_function, batched=True)
test_dataset = test_dataset.remove_columns([col for col in test_dataset.column_names if col not in ['input_ids', 'attention_mask']])
test_dataset.set_format(type='torch', columns=['input_ids', 'attention_mask'])

# Create the test_dataloader
test_dataloader = DataLoader(test_dataset, batch_size=16, shuffle=False)
# Determine the device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

# Move the model to the device
model = model.to(device)

# Set the model to evaluation mode
model.eval()

# Make predictions
all_predictions = []

with torch.no_grad():
    for batch in test_dataloader:
        inputs = {k: v.to(device) for k, v in batch.items()}
        outputs = model(**inputs)
        logits = outputs['logits']
        predictions = torch.sigmoid(logits).cpu().numpy()
        all_predictions.append(predictions)

# Concatenate all predictions
all_predictions = np.concatenate(all_predictions, axis=0)

# Convert predictions to binary (0 or 1)
binary_predictions = (all_predictions > 0.5).astype(int)

# Create submission DataFrame
submission = pd.DataFrame(binary_predictions, columns=emotion_columns)
submission['ID'] = test_data['ID']
submission = submission[['ID'] + emotion_columns]

# Save submission file
submission.to_csv('submission.csv', index=False)
print("Submission file created: submission.csv")

Map:   0%|          | 0/3259 [00:00<?, ? examples/s]

Using device: cuda
Submission file created: submission.csv
